import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "../global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "awesome",
  description: "Generated by awesome page",
};

export default function AwesomeLayout(
  { children }: Readonly<{ children: React.ReactNode; }>
 ) 
{
  return (
    <div className="rk">
        {children}
    </div>
  );
}
